### ISSUE TITLE
Thanks for Sharing

### ISSUE THREAD

**Issue by DeTeKe** [asle/hp_800_g1_mini_hackintosh#1]
I have a same model, But with 4gen mobile chip microcode.
currently boot with clover no issues https://github.com/DeTeKe/HP800G1DM_Hackintosh

**Comment by martintaborda** [comment]
Hi Asle! very nice job you did. I am using your info to try to install OS in my HP Elitedesk 800 G1 mini but unfortunately I cannot achive the installation.
I have a question... My CPU is an i5-4590T same CPU you did with the Lenovo M93p
May you tell me wich mix of files I shuould use in my pc?  I mean... SSDTs and and all this things.
Thanks so much in advance!
Regards, Martin.

**Comment by asle** [comment]
> Hi Asle! very nice job you did. I am using your info to try to install OS in my HP Elitedesk 800 G1 mini but unfortunately I cannot achive the installation.
> I have a question... My CPU is an i5-4590T same CPU you did with the Lenovo M93p
> May you tell me wich mix of files I shuould use in my pc? I mean... SSDTs and and all this things.
> Thanks so much in advance!
> Regards, Martin.

You can see what SSDTs I have in my EFI folder. I suggest using Windows on the HP 800 G1 to create these files with SSDTTIME. What is your problem? Have you tried to install with my EFI folder? Have you checked the BIOS settings? There should be no difference from i7 to your i5 cpu. You should use the same files in your EFI.

**Comment by martintaborda** [comment]
Thanks so much for your responde :) 

With your EFI file I had a some issues one of them incompatible CPU, I was not following the dortania's guide I was using gibMacOS but after the errors I decide to do the steps of dortania religiously. 

The SSDTs initially I was using your files but after I made my owns with SSDTTIME.

I have checked the config.plist in the sanity chequer and all is green, now I can go a little bit forward I am in the stage of recovey page to create the disk and all this things with graphic interface. But.... I assume that I am at this point because I have a black screen with the cursos I can move the cursor but all is black is like all it's happen behinds the scences hehe.

In device properties I have AAPL,ig-platform-id > 0300220D and device-id >12040000

I dont know what to do. Have you got some hint?
